services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
        volumes:
            - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        networks:
            - app-network

    php-fpm:
        image: php:8.3-fpm
        build:
            context: ./php
        container_name: php-fpm
        environment:
            - CI_ENV=development
        volumes:
            - ./app:/var/www/html
        networks:
            - app-network
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: dev
            MYSQL_PASSWORD: test
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./app/database/test_db.sql:/docker-entrypoint-initdb.d/init.sql # SQL file for initialization
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
